# Generated by Django 3.2.7 on 2021-12-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='Adama,Ethiopia', max_length=200),
            preserve_default=False,
        ),
    ]
