# Generated by Django 3.2.7 on 2021-12-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(default='images/project_images/logo3.png', upload_to='fiels'),
        ),
    ]
